name: Base CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assemble

  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run detekt with Gradle
        run: ./gradlew DndDetekt

  unit-tests-core:
    runs-on: ubuntu-latest
    needs: [ build, detekt ]
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run unit-tests for `:core`
        run: ./gradlew :shared:jvmTest

  unit-tests-cients-cli:
    runs-on: ubuntu-latest
    needs: [ build, detekt ]
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run unit-tests for `:core`
        run: ./gradlew :composeApp:desktopTest
